Updated to allow for terraform 1.0 Updated activate script to prevent being run twice

diff --git a/terraform-venv b/terraform-venv
--- a/terraform-venv
+++ b/terraform-venv
@@ -12,8 +12,8 @@ usage () {
   echo "$0 [<version>]" 1>&2
   echo "where: version is one of:" 1>&2
   echo "   {blank}:  use the most recent version" 1>&2
-  echo "   {major version}: use the most recent version, e.g. \"13\" = use the most recent 0.13.X" 1>&2
-  echo "   {major.minor version}: use the specific version, e.g. \"13.4\" = use version 0.13.4" 1>&2
+  echo "   {major version}: use the most recent version, e.g. \"0.13\" = use the most recent 0.13.X" 1>&2
+  echo "   {major.minor version}: use the specific version, e.g. \"0.13.4\" = use version 0.13.4" 1>&2
   exit 1
 }
 
@@ -25,21 +25,22 @@ fi
 if [ -n "$1" ]; then
   if [[ "$1" =~ ^[0-9\.]+$ ]]; then
      ver=$1
-     if [[ $ver =~ \. ]]; then
+     if [[ $ver =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        :
-     else
+     elif [[ $ver =~ ^[0-9]+\.[0-9]+$ ]]; then
        ver=$ver"."
+     else
+       ver=$ver".0."
      fi
-     ver="0."$ver
   else
-    echo "Version must be in format X or X.Y" 1>&2
+    echo "Version must be in format X.Y or X.Y.Z" 1>&2
     usage
     exit 1
   fi
 else
-  ver="0."
+  ver=
 fi
-tfver=$( curl -s https://releases.hashicorp.com/terraform/ | grep href | sed 's/.*>\(.*\)<.*/\1/' | grep terraform_ | grep ${ver//./\\.} | head -1 | sed 's/terraform_//' )
+tfver=$( curl -s https://releases.hashicorp.com/terraform/ | grep href | sed 's/.*>\(.*\)<.*/\1/' | grep terraform_${ver//./\\.} | head -1 | sed 's/terraform_//' )
 if [ -z "${tfver}" ]; then
   echo "Unable to find terraform version" 1>&2
   usage
@@ -83,17 +84,76 @@ cat >tf-activate <<-EOF 2> /dev/null
 # The following code is based on the virtualenv activation code from python
 # License: MIT License (MIT)
 # Original Author: Bernat Gabor (gaborjbernat@gmail.com)
-tf-deactivate () {
-    # reset old environment variables
-    if [ -n "\${_TFOLD_VIRTUAL_PATH:-}" ] ; then
-        PATH="\${_TFOLD_VIRTUAL_PATH:-}"
-        export PATH
-        unset _TFOLD_VIRTUAL_PATH
+
+if LC_ALL=C type tf-deactivate > /dev/null 2>/dev/null; then
+   echo "tf-venv is already activated, run \"tf-deactivate\" to deactivate before re-activating a new version" 1>&2
+else
+
+    tf-deactivate () {
+        # reset old environment variables
+        if [ -n "\${_TFOLD_VIRTUAL_PATH:-}" ] ; then
+            PATH="\${_TFOLD_VIRTUAL_PATH:-}"
+            export PATH
+            unset _TFOLD_VIRTUAL_PATH
+        fi
+        if [ -n "\${_TFOLD_VIRTUAL_HOME:-}" ] ; then
+            TFHOME="\${_TFOLD_VIRTUAL_HOME:-}"
+            export TFHOME
+            unset _TFOLD_VIRTUAL_HOME
+        fi
+
+        # This should detect bash and zsh, which have a hash command that must
+        # be called to get it to forget past commands.  Without forgetting
+        # past commands the \$PATH changes we made may not be respected
+        if [ -n "\${BASH:-}" -o -n "\${ZSH_VERSION:-}" ] ; then
+            hash -r
+        fi
+
+        if [ -n "\${_TFOLD_VIRTUAL_PS1:-}" ] ; then
+            PS1="\${_TFOLD_VIRTUAL_PS1:-}"
+            export PS1
+            unset _TFOLD_VIRTUAL_PS1
+        fi
+
+        unset TF_VIRTUAL_ENV
+        if [ ! "\${1:-}" = "nondestructive" ] ; then
+        # Self destruct!
+            unset -f tf-deactivate
+        fi
+    }
+
+    # unset irrelevant variables
+    tf-deactivate nondestructive
+
+    TF_VIRTUAL_ENV="$PWD"
+    export TF_VIRTUAL_ENV
+
+    _TFOLD_VIRTUAL_PATH="\$PATH"
+    PATH="\$TF_VIRTUAL_ENV:\$PATH"
+    export PATH
+
+    # unset TFHOME if set
+    # this will fail if TFHOME is set to the empty string (which is bad anyway)
+    # could use if (set -u; : \$TFHOME) ; in bash
+    if [ -n "\${TFHOME:-}" ] ; then
+        _TFOLD_VIRTUAL_TFHOME="\${TFHOME:-}"
+        unset TFHOME
     fi
-    if [ -n "\${_TFOLD_VIRTUAL_HOME:-}" ] ; then
-        TFHOME="\${_TFOLD_VIRTUAL_HOME:-}"
-        export TFHOME
-        unset _TFOLD_VIRTUAL_HOME
+
+    if [ -z "\${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
+        _TFOLD_VIRTUAL_PS1="\${PS1:-}"
+        if [ "x(TF " != x ] ; then
+	        PS1="(TF ${tfver}) \${PS1:-}"
+        else
+          if [ "\$(basename \"\$TF_VIRTUAL_ENV\")" = "__" ] ; then
+            # special case for Aspen magic directories
+            # see http://www.zetadev.com/software/aspen/
+            PS1="[\$(basename \`dirname \"\$TF_VIRTUAL_ENV\"\`)] \$PS1"
+          else
+            PS1="(\$(basename \"\$TF_VIRTUAL_ENV\"))\$PS1"
+          fi
+        fi
+        export PS1
     fi
 
     # This should detect bash and zsh, which have a hash command that must
@@ -102,61 +162,7 @@ tf-deactivate () {
     if [ -n "\${BASH:-}" -o -n "\${ZSH_VERSION:-}" ] ; then
         hash -r
     fi
-
-    if [ -n "\${_TFOLD_VIRTUAL_PS1:-}" ] ; then
-        PS1="\${_TFOLD_VIRTUAL_PS1:-}"
-        export PS1
-        unset _TFOLD_VIRTUAL_PS1
-    fi
-
-    unset TF_VIRTUAL_ENV
-    if [ ! "\${1:-}" = "nondestructive" ] ; then
-    # Self destruct!
-        unset -f tf-deactivate
-    fi
-}
-
-# unset irrelevant variables
-tf-deactivate nondestructive
-
-TF_VIRTUAL_ENV="$PWD"
-export TF_VIRTUAL_ENV
-
-_TFOLD_VIRTUAL_PATH="\$PATH"
-PATH="\$TF_VIRTUAL_ENV:\$PATH"
-export PATH
-
-# unset TFHOME if set
-# this will fail if TFHOME is set to the empty string (which is bad anyway)
-# could use if (set -u; : \$TFHOME) ; in bash
-if [ -n "\${TFHOME:-}" ] ; then
-    _TFOLD_VIRTUAL_TFHOME="\${TFHOME:-}"
-    unset TFHOME
 fi
-
-if [ -z "\${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
-    _TFOLD_VIRTUAL_PS1="\${PS1:-}"
-    if [ "x(TF " != x ] ; then
-	    PS1="(TF ${tfver}) \${PS1:-}"
-    else
-      if [ "\$(basename \"\$TF_VIRTUAL_ENV\")" = "__" ] ; then
-        # special case for Aspen magic directories
-        # see http://www.zetadev.com/software/aspen/
-        PS1="[\$(basename \`dirname \"\$TF_VIRTUAL_ENV\"\`)] \$PS1"
-      else
-        PS1="(\$(basename \"\$TF_VIRTUAL_ENV\"))\$PS1"
-      fi
-    fi
-    export PS1
-fi
-
-# This should detect bash and zsh, which have a hash command that must
-# be called to get it to forget past commands.  Without forgetting
-# past commands the \$PATH changes we made may not be respected
-if [ -n "\${BASH:-}" -o -n "\${ZSH_VERSION:-}" ] ; then
-    hash -r
-fi
-
 EOF
 chmod 755 tf-activate
 echo "Run: \"source tf-venv/tf-activate\" to activate"
